version: '3.8'

services:
  graphiti-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphiti-gemini-app
    ports:
      - "8000:8000"
    environment:
      # API Keys (будут переопределены в Dokploy)
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Neo4j Configuration
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-graphiti_password}
      
      # Gemini Configuration
      - GEMINI_MODEL=gemini-1.5-pro
      - GEMINI_TEMPERATURE=0.1
      
      # Application Settings
      - SEMAPHORE_LIMIT=5
      - MAX_RETRIES=3
      - DEBUG=false
      - USE_PARALLEL_RUNTIME=false
      - GRAPHITI_TELEMETRY_ENABLED=false
    depends_on:
      neo4j:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - graphiti-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  neo4j:
    image: neo4j:5.26-community
    container_name: graphiti-neo4j
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-graphiti_password}
      - NEO4J_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_dbms_memory_heap_initial_size=512m
      - NEO4J_dbms_memory_heap_max_size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      # Performance tuning
      - NEO4J_dbms_connector_bolt_thread_pool_min_size=5
      - NEO4J_dbms_connector_bolt_thread_pool_max_size=400
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    restart: unless-stopped
    networks:
      - graphiti-network
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p ${NEO4J_PASSWORD:-graphiti_password} 'RETURN 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  nginx:
    image: nginx:alpine
    container_name: graphiti-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - graphiti-app
    restart: unless-stopped
    networks:
      - graphiti-network

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local

networks:
  graphiti-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
