# Упрощенная версия без Nginx для быстрого тестирования
version: '3.8'

services:
  graphiti-app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-graphiti_password}
      - SEMAPHORE_LIMIT=5
    depends_on:
      - neo4j
    restart: unless-stopped

  neo4j:
    image: neo4j:5.26-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-graphiti_password}
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

volumes:
  neo4j_data:
